Repository oliverklee/ext-oelib, pull requests merged in 2020-11, with the labels that each got.

#403 [Task] Move the testing framework dummy files typo3 temp
  CHANGELOG.md
  Classes/TestingFramework.php
  Tests/Functional/Testing/FrameworkTest.php
  Tests/Unit/Testing/FrameworkTest.php
Labels: cleanup

#412 [TASK] Migrate all interfaces to proper namespaces
  Classes/BackEndLoginManager.php
  Classes/ConfigCheck.php
  Classes/Domain/Model/GermanZipCode.php
  Classes/Email/GeneralEmailRole.php
  Classes/FrontEndLoginManager.php
  Classes/Geocoding/Calculator.php
  Classes/Geocoding/Dummy.php
  Classes/Geocoding/Google.php
  Classes/Interfaces/Address.php
  Classes/Interfaces/ConfigurationCheckable.php
  Classes/Interfaces/Geo.php
  Classes/Interfaces/GeocodingLookup.php
  Classes/Interfaces/Identity.php
  Classes/Interfaces/LoginManager.php
  Classes/Interfaces/MailRole.php
  Classes/Interfaces/MapPoint.php
  Classes/Interfaces/Sortable.php
  Classes/List.php
  Classes/Mail.php
  Classes/Model.php
  Classes/Model/BackEndUser.php
  Classes/Model/FrontEndUser.php
  Classes/ViewHelpers/GoogleMapsViewHelper.php
  Migrations/Code/ClassAliasMap.php
  Migrations/Code/LegacyClassesForIde.php
  Tests/Unit/Configuration/ConfigurationCheckTest.php
  Tests/Unit/Configuration/Fixtures/DummyObjectToCheck.php
  Tests/Unit/Domain/Model/GermanZipCodeTest.php
  Tests/Unit/Email/Fixtures/TestingMailRole.php
  Tests/Unit/Email/GeneralEmailRoleTest.php
  Tests/Unit/Geocoding/Fixtures/TestingGeo.php
  Tests/Unit/Model/Fixtures/TestingChildModel.php
  Tests/Unit/ViewHelpers/Fixtures/TestingMapPoint.php
  Tests/Unit/ViewHelpers/GoogleMapsViewHelperTest.php
  composer.json
Labels: cleanup

#413 [TASK] Migrate all exceptions to proper namespaces
  Classes/DataMapper.php
  Classes/Db.php
  Classes/Exception/AccessDeniedException.php
  Classes/Exception/DatabaseException.php
  Classes/Exception/EmptyQueryResultException.php
  Classes/Exception/NotFoundException.php
  Classes/IdentityMap.php
  Classes/Mapper/BackEndUser.php
  Classes/Mapper/Country.php
  Classes/Mapper/Currency.php
  Classes/Mapper/FrontEndUser.php
  Classes/Mapper/Language.php
  Classes/MapperRegistry.php
  Classes/Model.php
  Classes/Model/FrontEndUser.php
  Classes/Template.php
  Classes/TemplateHelper.php
  Classes/TestingFramework.php
  Classes/ViewHelper/Price.php
  Migrations/Code/ClassAliasMap.php
  Migrations/Code/LegacyClassesForIde.php
  Tests/Functional/Database/DatabaseServiceTest.php
  Tests/Functional/Mapper/AbstractDataMapperTest.php
  Tests/Functional/Mapper/BackEndUserMapperTest.php
  Tests/Functional/Mapper/FrontEndUserMapperTest.php
  Tests/Unit/Exception/AccessDeniedExceptionTest.php
  Tests/Unit/Exception/DatabaseExceptionTest.php
  Tests/Unit/Exception/EmptyQueryResultExceptionTest.php
  Tests/Unit/Exception/NotFoundExceptionTest.php
  Tests/Unit/Mapper/AbstractDataMapperTest.php
  Tests/Unit/Mapper/Fixtures/TestingMapper.php
  Tests/Unit/Mapper/IdentityMapTest.php
  Tests/Unit/Model/AbstractModelTest.php
  Tests/Unit/Templating/TemplateTest.php
Labels: cleanup

#414 [TASK] Migrate UserWithoutCookies to proper namespace
  Classes/FrontEnd/UserWithoutCookies.php
  Classes/TestingFramework.php
  Migrations/Code/ClassAliasMap.php
  Migrations/Code/LegacyClassesForIde.php
Labels: cleanup

#415 [TASK] Migrate Geocoding to proper namespaces
  Classes/Geocoding/DummyGeocodingLookup.php
  Classes/Geocoding/GeoCalculcator.php
  Classes/Geocoding/GoogleGeocoding.php
  Classes/TestingFrameworkCleanup.php
  Migrations/Code/ClassAliasMap.php
  Migrations/Code/LegacyClassesForIde.php
  Tests/Unit/Geocoding/DummyGeocodingLookupTest.php
  Tests/Unit/Geocoding/GeoCalculcatorTest.php
  Tests/Unit/Geocoding/GoogleGeocodingTest.php
Labels: cleanup

#423 [TASK] Migrate the mapper to proper namespace
  Classes/BackEndLoginManager.php
  Classes/FrontEndLoginManager.php
  Classes/Mapper/BackEndUserGroupMapper.php
  Classes/Mapper/BackEndUserMapper.php
  Classes/Mapper/CountryMapper.php
  Classes/Mapper/CurrencyMapper.php
  Classes/Mapper/FederalStateMapper.php
  Classes/Mapper/FrontEndUserGroupMapper.php
  Classes/Mapper/FrontEndUserMapper.php
  Classes/Mapper/LanguageMapper.php
  Classes/Model/FrontEndUser.php
  Classes/TestingFramework.php
  Classes/ViewHelper/Price.php
  Documentation/Tutorial/UsingAndPersistingDomainModels/Index.rst
  Migrations/Code/ClassAliasMap.php
  Migrations/Code/LegacyClassesForIde.php
  Tests/Functional/Authentication/BackEndLoginManagerTest.php
  Tests/Functional/Authentication/FrontEndLoginManagerTest.php
  Tests/Functional/Mapper/BackEndUserGroupMapperTest.php
  Tests/Functional/Mapper/BackEndUserMapperTest.php
  Tests/Functional/Mapper/CountryMapperTest.php
  Tests/Functional/Mapper/CurrencyMapperTest.php
  Tests/Functional/Mapper/FederalStateMapperTest.php
  Tests/Functional/Mapper/FrontEndUserGroupMapperTest.php
  Tests/Functional/Mapper/FrontEndUserMapperTest.php
  Tests/Functional/Mapper/LanguageMapperTest.php
  Tests/Functional/Model/BackEndUserTest.php
  Tests/Functional/Model/FrontEndUserTest.php
  Tests/Unit/Mapper/Fixtures/TestingMapper.php
  Tests/Unit/Model/FrontEndUserTest.php
Labels: cleanup

#425 [TASK] Migrate Models to proper namespaces
  Classes/BackEndLoginManager.php
  Classes/FrontEndLoginManager.php
  Classes/Mapper/BackEndUserGroupMapper.php
  Classes/Mapper/BackEndUserMapper.php
  Classes/Mapper/CountryMapper.php
  Classes/Mapper/CurrencyMapper.php
  Classes/Mapper/FederalStateMapper.php
  Classes/Mapper/FrontEndUserGroupMapper.php
  Classes/Mapper/FrontEndUserMapper.php
  Classes/Mapper/LanguageMapper.php
  Classes/Model/BackEndUser.php
  Classes/Model/BackEndUserGroup.php
  Classes/Model/Country.php
  Classes/Model/Currency.php
  Classes/Model/FederalState.php
  Classes/Model/FrontEndUser.php
  Classes/Model/FrontEndUserGroup.php
  Classes/Model/Language.php
  Classes/ViewHelper/Price.php
  Migrations/Code/ClassAliasMap.php
  Migrations/Code/LegacyClassesForIde.php
  Tests/Functional/Authentication/BackEndLoginManagerTest.php
  Tests/Functional/Authentication/FrontEndLoginManagerTest.php
  Tests/Functional/Language/TranslatorRegistryTest.php
  Tests/Functional/Mapper/AbstractDataMapperTest.php
  Tests/Functional/Mapper/BackEndUserGroupMapperTest.php
  Tests/Functional/Mapper/BackEndUserMapperTest.php
  Tests/Functional/Mapper/CountryMapperTest.php
  Tests/Functional/Mapper/CurrencyMapperTest.php
  Tests/Functional/Mapper/FederalStateMapperTest.php
  Tests/Functional/Mapper/FrontEndUserGroupMapperTest.php
  Tests/Functional/Mapper/FrontEndUserMapperTest.php
  Tests/Functional/Mapper/LanguageMapperTest.php
  Tests/Functional/Model/BackEndUserTest.php
  Tests/Functional/Model/FrontEndUserTest.php
  Tests/Unit/Authentication/FrontEndLoginManagerTest.php
  Tests/Unit/Model/BackEndUserGroupTest.php
  Tests/Unit/Model/BackEndUserTest.php
  Tests/Unit/Model/CountryTest.php
  Tests/Unit/Model/CurrencyTest.php
  Tests/Unit/Model/FederalStateTest.php
  Tests/Unit/Model/Fixtures/TestingModel.php
  Tests/Unit/Model/FrontEndUserGroupTest.php
  Tests/Unit/Model/FrontEndUserTest.php
  Tests/Unit/Model/LanguageTest.php
Labels: cleanup

#426 [TASK] Migrate viewhelpers to proper namespace
  Classes/ViewHelpers/GoogleMapsViewHelper.php
  Classes/ViewHelpers/PriceViewhelper.php
  Classes/ViewHelpers/UppercaseViewHelper.php
  Migrations/Code/ClassAliasMap.php
  Migrations/Code/LegacyClassesForIde.php
  Tests/Functional/ViewHelpers/PriceViewHelperTest.php
  Tests/Unit/ViewHelpers/GoogleMapsViewHelperTest.php
  Tests/Unit/ViewHelpers/PriceViewHelperTest.php
  Tests/Unit/ViewHelpers/UppercaseViewHelperTest.php
Labels: cleanup

#428 [TASK] Migrate Visibilities to proper namespace
  Classes/Visibility/Node.php
  Classes/Visibility/Tree.php
  Migrations/Code/ClassAliasMap.php
  Migrations/Code/LegacyClassesForIde.php
  Tests/Unit/Visibility/NodeTest.php
  Tests/Unit/Visibility/TreeTest.php
Labels: cleanup

#430 [CLEANUP] Code formatting cleanup
  Classes/Geocoding/DummyGeocodingLookup.php
  Classes/Geocoding/GoogleGeocoding.php
  Classes/Mapper/CountryMapper.php
  Classes/Mapper/CurrencyMapper.php
Labels: cleanup

#432 [FEATURE] Add an .editorconfig file
  .editorconfig
  .gitattributes
  CHANGELOG.md
Labels: enhancement

#433 [BUGFIX] Fix Composer cache keys in the CI configuration file
  .github/workflows/ci.yml
  CHANGELOG.md
Labels: bug

#436 [CLEANUP] Migrate DataMapper and MapperRegistry to proper namespace
  Classes/Mapper/AbstractDataMapper.php
  Classes/Mapper/BackEndUserGroupMapper.php
  Classes/Mapper/BackEndUserMapper.php
  Classes/Mapper/CountryMapper.php
  Classes/Mapper/CurrencyMapper.php
  Classes/Mapper/FederalStateMapper.php
  Classes/Mapper/FrontEndUserGroupMapper.php
  Classes/Mapper/FrontEndUserMapper.php
  Classes/Mapper/LanguageMapper.php
  Classes/Mapper/MapperRegistry.php
  Classes/Model.php
  Documentation/Tutorial/UsingAndPersistingDomainModels/Index.rst
  Migrations/Code/ClassAliasMap.php
  Migrations/Code/LegacyClassesForIde.php
  Tests/Unit/Mapper/Fixtures/ColumnLessTestingMapper.php
  Tests/Unit/Mapper/Fixtures/ModelLessTestingMapper.php
  Tests/Unit/Mapper/Fixtures/TableLessTestingMapper.php
  Tests/Unit/Mapper/Fixtures/TestingChildMapper.php
  Tests/Unit/Mapper/Fixtures/TestingMapper.php
Labels: cleanup

#438 [CLEANUP] Migrate Tx_Oelib_Model to proper namespace
  Classes/Geocoding/GeoCalculcator.php
  Classes/IdentityMap.php
  Classes/Interfaces/LoginManager.php
  Classes/Mapper/AbstractDataMapper.php
  Classes/Model/AbstractModel.php
  Classes/Model/BackEndUser.php
  Classes/Model/BackEndUserGroup.php
  Classes/Model/Country.php
  Classes/Model/Currency.php
  Classes/Model/FederalState.php
  Classes/Model/FrontEndUser.php
  Classes/Model/FrontEndUserGroup.php
  Classes/Model/Language.php
  Migrations/Code/ClassAliasMap.php
  Migrations/Code/LegacyClassesForIde.php
  Tests/Functional/Mapper/AbstractDataMapperTest.php
  Tests/Functional/Model/AbstractModelTest.php
  Tests/Unit/DataStructures/ListTest.php
  Tests/Unit/Geocoding/Fixtures/TestingGeo.php
  Tests/Unit/Mapper/AbstractDataMapperTest.php
  Tests/Unit/Mapper/Fixtures/TestingMapper.php
  Tests/Unit/Model/AbstractModelTest.php
  Tests/Unit/Model/Fixtures/ReadOnlyModel.php
  Tests/Unit/Model/Fixtures/TestingChildModel.php
  Tests/Unit/Model/Fixtures/TestingModel.php
Labels: cleanup

#439 [CLEANUP] Do not import global classes
  Classes/Model/AbstractModel.php
Labels: cleanup

#440 [CLEANUP] Migrate all occurences of Tx_Oelib_MapperRegistry to
  Classes/BackEndLoginManager.php
  Classes/FrontEndLoginManager.php
  Classes/Mapper/AbstractDataMapper.php
  Classes/Mapper/MapperRegistry.php
  Classes/Model/FrontEndUser.php
  Classes/TestingFramework.php
  Classes/TestingFrameworkCleanup.php
  Classes/ViewHelpers/PriceViewhelper.php
  Documentation/Tutorial/UsingAndPersistingDomainModels/Index.rst
  Tests/Functional/Authentication/BackEndLoginManagerTest.php
  Tests/Functional/Authentication/FrontEndLoginManagerTest.php
  Tests/Functional/Mapper/AbstractDataMapperTest.php
  Tests/Functional/Mapper/BackEndUserMapperTest.php
  Tests/Functional/Mapper/FrontEndUserMapperTest.php
  Tests/Functional/Model/AbstractModelTest.php
  Tests/Functional/Model/BackEndUserTest.php
  Tests/Functional/Model/FrontEndUserTest.php
  Tests/Unit/Mapper/AbstractDataMapperTest.php
  Tests/Unit/Mapper/MapperRegistryTest.php
  Tests/Unit/Model/FrontEndUserTest.php
Labels: cleanup

#441 [CLEANUP][FOLLOWUP] Migrate left over Tx_Oelib_Model to namespaced class
  Classes/List.php
  Classes/Mapper/AbstractDataMapper.php
  Documentation/Tutorial/UsingAndPersistingDomainModels/Index.rst
Labels: cleanup

#437 [CLEANUP] Fix the casing of "PriceViewHelper"
  Classes/ViewHelpers/PriceViewHelper.php
  Migrations/Code/ClassAliasMap.php
  Migrations/Code/LegacyClassesForIde.php
  Tests/Functional/ViewHelpers/PriceViewHelperTest.php
  Tests/Unit/ViewHelpers/PriceViewHelperTest.php
Labels: cleanup

#444 [CLEANUP] Migrate objects to proper namespaces
  Classes/Configuration.php
  Classes/ConfigurationProxy.php
  Classes/DataStructures/AbstractObjectWithAccessors.php
  Classes/DataStructures/AbstractObjectWithPublicAccessors.php
  Classes/DataStructures/Collection.php
  Classes/Geocoding/GeoCalculcator.php
  Classes/Mail.php
  Classes/Mapper/AbstractDataMapper.php
  Classes/Mapper/FrontEndUserMapper.php
  Classes/Model/AbstractModel.php
  Classes/Model/BackEndUser.php
  Classes/Model/BackEndUserGroup.php
  Classes/Model/FrontEndUser.php
  Classes/Session.php
  Classes/TestingFramework.php
  Migrations/Code/ClassAliasMap.php
  Migrations/Code/LegacyClassesForIde.php
  Tests/Functional/Mapper/AbstractDataMapperTest.php
  Tests/Functional/Mapper/FrontEndUserMapperTest.php
  Tests/Functional/Model/BackEndUserTest.php
  Tests/Unit/Configuration/ConfigurationProxyTest.php
  Tests/Unit/DataStructures/CollectionTest.php
  Tests/Unit/DataStructures/Fixtures/TestingObject.php
  Tests/Unit/Email/Fixtures/TestingMailRole.php
  Tests/Unit/Geocoding/GeoCalculcatorTest.php
  Tests/Unit/Mapper/Fixtures/TestingMapper.php
  Tests/Unit/Model/AbstractModelTest.php
  Tests/Unit/Model/BackEndUserGroupTest.php
  Tests/Unit/Model/BackEndUserTest.php
  Tests/Unit/Model/Fixtures/TestingModel.php
  Tests/Unit/Model/FrontEndUserTest.php
Labels: cleanup

#443 [CLEANUP] Migrate Tx_Oelib_IdentityMap to Mapper namespace
  Classes/Mapper/AbstractDataMapper.php
  Classes/Mapper/IdentityMap.php
  Migrations/Code/ClassAliasMap.php
  Migrations/Code/LegacyClassesForIde.php
  Tests/Unit/Mapper/AbstractDataMapperTest.php
  Tests/Unit/Mapper/Fixtures/TestingMapper.php
  Tests/Unit/Mapper/IdentityMapTest.php
Labels: cleanup

#446 [FOLLOWUP] Do not import classes from the global namespace
  Classes/DataStructures/Collection.php
Labels: cleanup

#448 [CLEANUP] Migrate the FE-/BELoginManager to proper namespace
  Classes/Authentication/BackEndLoginManager.php
  Classes/Authentication/FrontEndLoginManager.php
  Classes/Mapper/BackEndUserMapper.php
  Classes/TestingFramework.php
  Classes/TestingFrameworkCleanup.php
  Classes/TranslatorRegistry.php
  Migrations/Code/ClassAliasMap.php
  Migrations/Code/LegacyClassesForIde.php
  Tests/Functional/Authentication/BackEndLoginManagerTest.php
  Tests/Functional/Authentication/FrontEndLoginManagerTest.php
  Tests/Functional/Language/TranslatorRegistryTest.php
  Tests/Functional/Testing/FrameworkTest.php
  Tests/Unit/Authentication/BackEndLoginManagerTest.php
  Tests/Unit/Authentication/FrontEndLoginManagerTest.php
Labels: cleanup

#449 [CLEANUP] Migrate config related files to proper namespace
  Classes/Configuration/Configuration.php
  Classes/Configuration/ConfigurationCheck.php
  Classes/Configuration/ConfigurationProxy.php
  Classes/Configuration/ConfigurationRegistry.php
  Classes/Configuration/PageFinder.php
  Classes/Geocoding/GoogleGeocoding.php
  Classes/TemplateHelper.php
  Classes/TestingFrameworkCleanup.php
  Classes/TranslatorRegistry.php
  Classes/ViewHelpers/GoogleMapsViewHelper.php
  Migrations/Code/ClassAliasMap.php
  Migrations/Code/LegacyClassesForIde.php
  Tests/Functional/Configuration/ConfigurationCheckTest.php
  Tests/Functional/Configuration/ConfigurationRegistryTest.php
  Tests/Functional/Configuration/PageFinderTest.php
  Tests/Functional/Language/TranslatorRegistryTest.php
  Tests/Functional/Templating/TemplateHelperTest.php
  Tests/Unit/Configuration/ConfigurationCheckTest.php
  Tests/Unit/Configuration/ConfigurationProxyTest.php
  Tests/Unit/Configuration/ConfigurationRegistryTest.php
  Tests/Unit/Configuration/ConfigurationTest.php
  Tests/Unit/Configuration/PageFinderTest.php
  Tests/Unit/Geocoding/GoogleGeocodingTest.php
  Tests/Unit/Templating/Fixtures/TestingConfigurationCheck.php
  Tests/Unit/Templating/TemplateHelperTest.php
  Tests/Unit/ViewHelpers/GoogleMapsViewHelperTest.php
Labels: cleanup

#453 [CLEANUP] Move Header classes to proper namespace
  Classes/Http/HeaderCollector.php
  Classes/Http/HeaderProxyFactory.php
  Classes/Http/Interfaces/HeaderProxy.php
  Classes/Http/RealHeaderProxy.php
  Classes/TestingFrameworkCleanup.php
  Documentation/Tutorial/StoreHttpHeadersForTestingThemInsteadOfSendingThem/Index.rst
  Migrations/Code/ClassAliasMap.php
  Migrations/Code/LegacyClassesForIde.php
  Tests/Unit/Http/HeaderProxyFactoryTest.php
Labels: cleanup

#452 [TASK] Add Migrations/ to the PHP QualityTools
  Migrations/Code/ClassAliasMap.php
  Migrations/Code/LegacyClassesForIde.php
  composer.json
Labels: enhancement

#454 [CLEANUP] Rename Tx_Oelib_Db and migrate to proper namespace
  Classes/Database/DatabaseService.php
  Classes/Mapper/AbstractDataMapper.php
  Migrations/Code/ClassAliasMap.php
  Migrations/Code/LegacyClassesForIde.php
  Tests/Functional/Database/DatabaseServiceTest.php
Labels: cleanup

#455 [CLEANUP] Move language related classes to proper namespace
  Classes/Language/SalutationSwitcher.php
  Classes/Language/Translator.php
  Classes/Language/TranslatorRegistry.php
  Classes/Template.php
  Classes/TemplateHelper.php
  Classes/TestingFrameworkCleanup.php
  Migrations/Code/ClassAliasMap.php
  Migrations/Code/LegacyClassesForIde.php
  Tests/Functional/Language/TranslatorRegistryTest.php
  Tests/Unit/Language/Fixtures/TestingSalutationSwitcher.php
  Tests/Unit/Language/TranslatorTest.php
  Tests/Unit/Templating/TemplateTest.php
Labels: cleanup

#456 [CLEANUP] Migrate mail related classes to proper namespace
  Classes/Mail/AbstractMailer.php
  Classes/Mail/Attachment.php
  Classes/Mail/EmailCollector.php
  Classes/Mail/Mail.php
  Classes/Mail/MailerFactory.php
  Classes/Mail/RealMailer.php
  Classes/TestingFrameworkCleanup.php
  Migrations/Code/ClassAliasMap.php
  Migrations/Code/LegacyClassesForIde.php
  Tests/Functional/Email/AbstractMailerTest.php
  Tests/Functional/Email/MailTest.php
  Tests/Unit/Email/AbstractMailerTest.php
  Tests/Unit/Email/AttachmentTest.php
  Tests/Unit/Email/MailTest.php
  Tests/Unit/Email/MailerFactoryTest.php
  Tests/Unit/Email/RealMailerTest.php
Labels: cleanup

#457 [BUGFIX] Fix the path to the bundled autoload.php
  Classes/Mail/Mail.php
Labels: bug

#458 [CLEANUP] Migrate session classes to proper namespace
  Classes/Session/FakeSession.php
  Classes/Session/Session.php
  Classes/TestingFrameworkCleanup.php
  Migrations/Code/ClassAliasMap.php
  Migrations/Code/LegacyClassesForIde.php
  Tests/Unit/Session/FakeSessionTest.php
  Tests/Unit/Session/SessionTest.php
Labels: cleanup

#459 [TASK] Drop TemplateHelper::setCachedConfigurationValue
  CHANGELOG.md
  Classes/TemplateHelper.php
  Tests/Unit/Templating/TemplateHelperTest.php
Labels: bug, cleanup

#460 [BUGFIX] Fix typo in class name "Calculcator"
  Classes/Geocoding/GeoCalculator.php
  Migrations/Code/ClassAliasMap.php
  Migrations/Code/LegacyClassesForIde.php
  Tests/Unit/Geocoding/GeoCalculatorTest.php
Labels: bug

#461 [CLEANUP] Move the TestingTemplateHelper
  Tests/Functional/Templating/TemplateHelperTest.php
  Tests/Functional/Testing/FrameworkTest.php
  Tests/Unit/Templating/Fixtures/TestingTemplateHelper.php
  Tests/Unit/Templating/TemplateHelperTest.php
Labels: cleanup

#463 [CLEANUP] Move the TemplateHelper to namespaces
  Classes/Configuration/ConfigurationCheck.php
  Classes/Templating/TemplateHelper.php
  Classes/TestingFrameworkCleanup.php
  Migrations/Code/ClassAliasMap.php
  Migrations/Code/LegacyClassesForIde.php
  Tests/Unit/Configuration/Fixtures/DummyObjectToCheck.php
  Tests/Unit/Templating/Fixtures/PluginWithCustomConfigurationCheck.php
  Tests/Unit/Templating/Fixtures/TestingTemplateHelper.php
  Tests/Unit/Templating/TemplateHelperTest.php
Labels: cleanup

#474 [CLEANUP] Stop using the non-namespaced oelib classes
  Classes/Model/AbstractModel.php
  Classes/Model/FrontEndUser.php
Labels: cleanup

#475 [CLEANUP] Migrate template related classes to proper namespace
  Classes/Templating/Template.php
  Classes/Templating/TemplateHelper.php
  Classes/Templating/TemplateRegistry.php
  Classes/Visibility/Tree.php
  Documentation/Tutorial/UsingTheTemplateHelperAndSalutationSwitching/Index.rst
  Migrations/Code/ClassAliasMap.php
  Migrations/Code/LegacyClassesForIde.php
  Tests/Unit/Templating/TemplateRegistryTest.php
  Tests/Unit/Templating/TemplateTest.php
Labels: cleanup

#476 [CLEANUP] Move testing related classes to proper namespace
  Classes/Mapper/AbstractDataMapper.php
  Classes/Mapper/MapperRegistry.php
  Classes/Tests/TestingFramework.php
  Classes/Tests/TestingFrameworkCleanup.php
  Migrations/Code/ClassAliasMap.php
  Migrations/Code/LegacyClassesForIde.php
  Tests/Functional/Authentication/FrontEndLoginManagerTest.php
  Tests/Functional/Configuration/ConfigurationCheckTest.php
  Tests/Functional/Configuration/ConfigurationRegistryTest.php
  Tests/Functional/Configuration/PageFinderTest.php
  Tests/Functional/Mapper/AbstractDataMapperTest.php
  Tests/Functional/Mapper/BackEndUserMapperTest.php
  Tests/Functional/Mapper/FrontEndUserGroupMapperTest.php
  Tests/Functional/Testing/TestingFrameworkTest.php
  Tests/Unit/Configuration/PageFinderTest.php
  Tests/Unit/Testing/TestingFrameworkTest.php
  ext_localconf.php
Labels: cleanup

#479 [CLEANUP] Sort the helper classes, update documentation and fix test
  Documentation/Tutorial/UsingAndPersistingDomainModels/Index.rst
  Documentation/Tutorial/UsingTheConfigurationProxy/Index.rst
  Documentation/Tutorial/UsingThePriceViewHelper/Index.rst
  Documentation/Tutorial/UsingTheVisibilityTreeForShowingAndHidingNestedSubparts/Index.rst
  Migrations/Code/ClassAliasMap.php
  Migrations/Code/LegacyClassesForIde.php
  Tests/Unit/Mapper/MapperRegistryTest.php
Labels: cleanup

#481 [CLEANUP] Rename the "Mail" namespace to "Email"
  Classes/Email/AbstractMailer.php
  Classes/Email/Attachment.php
  Classes/Email/EmailCollector.php
  Classes/Email/Mail.php
  Classes/Email/MailerFactory.php
  Classes/Email/RealMailer.php
  Classes/Tests/TestingFrameworkCleanup.php
  Migrations/Code/ClassAliasMap.php
  Migrations/Code/LegacyClassesForIde.php
  Tests/Functional/Email/AbstractMailerTest.php
  Tests/Functional/Email/MailTest.php
  Tests/Unit/Email/AbstractMailerTest.php
  Tests/Unit/Email/AttachmentTest.php
  Tests/Unit/Email/MailTest.php
  Tests/Unit/Email/MailerFactoryTest.php
  Tests/Unit/Email/RealMailerTest.php
Labels: cleanup

#482 [CLEANUP] Rename the Tests namespace to Testing
  Classes/Mapper/AbstractDataMapper.php
  Classes/Mapper/MapperRegistry.php
  Classes/Testing/TestingFramework.php
  Classes/Testing/TestingFrameworkCleanup.php
  Migrations/Code/ClassAliasMap.php
  Migrations/Code/LegacyClassesForIde.php
  Tests/Functional/Authentication/FrontEndLoginManagerTest.php
  Tests/Functional/Configuration/ConfigurationCheckTest.php
  Tests/Functional/Configuration/ConfigurationRegistryTest.php
  Tests/Functional/Configuration/PageFinderTest.php
  Tests/Functional/Mapper/AbstractDataMapperTest.php
  Tests/Functional/Mapper/BackEndUserMapperTest.php
  Tests/Functional/Mapper/FrontEndUserGroupMapperTest.php
  Tests/Functional/Testing/TestingFrameworkTest.php
  Tests/Unit/Testing/TestingFrameworkTest.php
  ext_localconf.php
Labels: cleanup
