Repository oliverklee/ext-oelib, pull requests merged in 2020-12, with the labels that each got.

#485 [CLEANUP] Make the type annotations for arrays more specific
  Classes/Configuration/ConfigurationProxy.php
  Classes/Configuration/ConfigurationRegistry.php
  Classes/DataStructures/Collection.php
  Classes/Database/DatabaseService.php
  Classes/Domain/Model/GermanZipCode.php
  Classes/Domain/Model/Traits/CachedAssociationCount.php
  Classes/Domain/Repository/GermanZipCodeRepository.php
  Classes/Email/EmailCollector.php
  Classes/Email/Mail.php
  Classes/Geocoding/DummyGeocodingLookup.php
  Classes/Interfaces/Geo.php
  Classes/Interfaces/MapPoint.php
  Classes/Language/SalutationSwitcher.php
  Classes/Language/Translator.php
  Classes/Language/TranslatorRegistry.php
  Classes/Mapper/AbstractDataMapper.php
  Classes/Mapper/BackEndUserGroupMapper.php
  Classes/Mapper/BackEndUserMapper.php
  Classes/Mapper/CountryMapper.php
  Classes/Mapper/FrontEndUserMapper.php
  Classes/Mapper/IdentityMap.php
  Classes/Mapper/MapperRegistry.php
  Classes/Model/BackEndUser.php
  Classes/Session/FakeSession.php
  Classes/Session/Session.php
  Classes/Templating/Template.php
  Classes/Templating/TemplateHelper.php
  Classes/Templating/TemplateRegistry.php
  Classes/Testing/TestingFramework.php
  Classes/Visibility/Node.php
Labels: cleanup

#491 [TASK] Remove calls to initLLvars()
  Tests/Functional/Language/TranslatorRegistryTest.php
Labels: cleanup

#494 [BUGFIX] Fix capitalization of namespaces
  Classes/FrontEnd/UserWithoutCookies.php
  Classes/Testing/TestingFramework.php
Labels: bug

#493 [TASK] Remove namespace sniff exclusions and define PSR4
  composer.json
  ext_emconf.php
  phpcs.xml.dist
Labels: cleanup

#496 [BUGFIX] More followup to namespacing all classes
  Classes/Testing/TestingFramework.php
  Migrations/Code/ClassAliasMap.php
  Migrations/Code/LegacyClassesForIde.php
Labels: bug

#500 [CLEANUP] Add type annotations when using makeInstance
  Classes/Authentication/FrontEndLoginManager.php
  Classes/Database/DatabaseService.php
  Classes/Email/SystemEmailFromBuilder.php
  Classes/Mapper/AbstractDataMapper.php
  Classes/Testing/TestingFramework.php
Labels: cleanup

#502 [BUGFIX] Add necessary int casts
  CHANGELOG.md
  Classes/Mapper/AbstractDataMapper.php
  Classes/Model/FrontEndUser.php
Labels: bug

#503 [CLEANUP] Fix some PHPDoc type annotations
  Classes/Configuration/Configuration.php
  Classes/Language/Translator.php
  Classes/Model/AbstractModel.php
  Classes/Testing/TestingFramework.php
  Tests/Functional/Testing/TestingFrameworkTest.php
  Tests/Unit/DataStructures/Fixtures/TestingObject.php
  Tests/Unit/Email/AbstractMailerTest.php
  Tests/Unit/Mapper/Fixtures/TestingMapper.php
Labels: cleanup

#504 [BUGFIX] Use correct cache keys in TYPO3 10LTS
  CHANGELOG.md
  Classes/Testing/TestingFramework.php
Labels: bug

#508 [CLEANUP] Remove call to initTemplate()
  Classes/Testing/TestingFramework.php
Labels: bug, cleanup

#507 [CLEANUP] Stop calling $page->getRootLine in TYPO3 V9
  Classes/Configuration/ConfigurationRegistry.php
  Classes/Templating/TemplateHelper.php
  Classes/Testing/TestingFramework.php
Labels: bug, cleanup

#501 [CLEANUP] Add more type declarations
  CHANGELOG.md
  Classes/Authentication/BackEndLoginManager.php
  Classes/Authentication/FrontEndLoginManager.php
  Classes/Configuration/Configuration.php
  Classes/Configuration/ConfigurationProxy.php
  Classes/DataStructures/AbstractObjectWithAccessors.php
  Classes/DataStructures/AbstractObjectWithPublicAccessors.php
  Classes/DataStructures/Collection.php
  Classes/Domain/Model/GermanZipCode.php
  Classes/Domain/Model/Traits/CachedAssociationCount.php
  Classes/Email/GeneralEmailRole.php
  Classes/Email/Mail.php
  Classes/FrontEnd/UserWithoutCookies.php
  Classes/Interfaces/Identity.php
  Classes/Interfaces/LoginManager.php
  Classes/Interfaces/MapPoint.php
  Classes/Interfaces/Sortable.php
  Classes/Language/SalutationSwitcher.php
  Classes/Mapper/AbstractDataMapper.php
  Classes/Mapper/BackEndUserMapper.php
  Classes/Mapper/CountryMapper.php
  Classes/Model/AbstractModel.php
  Classes/Model/BackEndUser.php
  Classes/Model/FrontEndUser.php
  Classes/Session/FakeSession.php
  Classes/Session/Session.php
  Classes/Templating/TemplateHelper.php
  Tests/Functional/Mapper/AbstractDataMapperTest.php
  Tests/Unit/DataStructures/Fixtures/TestingObject.php
  Tests/Unit/Email/Fixtures/TestingMailRole.php
  Tests/Unit/Geocoding/Fixtures/TestingGeo.php
  Tests/Unit/Geocoding/GeoCalculatorTest.php
  Tests/Unit/Geocoding/GoogleGeocodingTest.php
  Tests/Unit/Mapper/Fixtures/TestingMapper.php
  Tests/Unit/Model/Fixtures/TestingChildModel.php
  Tests/Unit/Model/Fixtures/TestingModel.php
  Tests/Unit/ViewHelpers/Fixtures/TestingMapPoint.php
Labels: cleanup

#506 [CLEANUP] Update the configuration proxy to the new configuration format
  CHANGELOG.md
  Classes/Configuration/ConfigurationProxy.php
Labels: bug, cleanup, enhancement

#509 [CLEANUP] Stop accessing deprecated TypoScriptFrontendController properties in TYPO3 9
  Classes/Testing/TestingFramework.php
Labels: cleanup

#510 [BUGFIX] Harden unserialize calls of extension configuration
  CHANGELOG.md
  Classes/Configuration/ConfigurationProxy.php
  Classes/Model/BackEndUser.php
Labels: bug

#511 [CLEANUP] Stop accessing deprecated TypoScriptFrontendController properties
  Classes/Testing/TestingFramework.php
Labels: cleanup

#513 [CLEANUP] Stop calling $template->init in TYPO3 V9
  Classes/Configuration/ConfigurationRegistry.php
  Classes/Templating/TemplateHelper.php
Labels: cleanup

#515 [CLEANUP] Use `Typo3Version::isNotHigherThan(8)` for version checking
  Tests/Functional/Testing/TestingFrameworkTest.php
Labels: cleanup

#512 [CLEANUP] Stop using tmpl->getFileName
  Classes/Configuration/ConfigurationCheck.php
  Classes/Templating/TemplateHelper.php
Labels: cleanup

#516 [CLEANUP] Throw version-dependent deprecation warnings
  Classes/Configuration/ConfigurationCheck.php
Labels: cleanup

#520 [BUGFIX] Fix the seconds per year constant
  Classes/Interfaces/Time.php
Labels: bug

#518 [TASK] Add test for the constants in Time interface
  Tests/Unit/Interfaces/TimeTest.php
Labels: enhancement

#522 [FEATURE] Add a PageRepository
  CHANGELOG.md
  Classes/Database/DatabaseService.php
  Classes/Domain/Repository/PageRepository.php
  Tests/Functional/Domain/Repository/Fixtures/NestedPages.xml
  Tests/Functional/Domain/Repository/PageRepositoryTest.php
  Tests/Unit/Domain/Repository/PageRepositoryTest.php
Labels: enhancement

#524 [CLEANUP] Harden null checks
  CHANGELOG.md
  Classes/Configuration/ConfigurationCheck.php
  Classes/Configuration/ConfigurationRegistry.php
  Classes/Configuration/PageFinder.php
  Classes/Database/DatabaseService.php
  Classes/Email/Mail.php
  Classes/Email/MailerFactory.php
  Classes/Geocoding/GoogleGeocoding.php
  Classes/Mapper/AbstractDataMapper.php
  Classes/Model/FrontEndUser.php
  Classes/Session/Session.php
  Classes/Templating/Template.php
  Classes/Templating/TemplateHelper.php
  Classes/ViewHelpers/PriceViewHelper.php
Labels: cleanup

#525 [BUGFIX] Fix the constant for one degree latitude
  Classes/Geocoding/GeoCalculator.php
  Tests/Unit/Geocoding/GeoCalculatorTest.php
Labels: bug

#528 [BUGFIX] Restore TemplateHelper::setCachedConfigurationValue
  CHANGELOG.md
  Classes/Templating/TemplateHelper.php
  Tests/Unit/Templating/TemplateHelperTest.php
Labels: bug
