Repository oliverklee/ext-oelib, pull requests merged in 2022-11, with the labels that each got.

#1236 Deprecate the LazyLoadingProperties trait
  CHANGELOG.md
  Classes/Domain/Model/Traits/LazyLoadingProperties.php
Labels: hacktoberfest

#1255 [TASK] Stop using Prophecy in the domain unit tests
  CHANGELOG.md
  Tests/Unit/Domain/Model/Traits/CachedAssociationCountTest.php
  Tests/Unit/Domain/Model/Traits/LazyLoadingPropertiesTest.php
  Tests/Unit/Domain/Repository/GermanZipCodeRepositoryTest.php
  Tests/Unit/Domain/Repository/Traits/DirectPersistTest.php
Labels: cleanup

#1257 [TASK] Replace the remaining Prophecy usages in unit tests
  CHANGELOG.md
  Tests/Unit/Configuration/AbstractConfigurationCheckTest.php
  Tests/Unit/Logging/Traits/LoggingAwareTest.php
  Tests/Unit/Session/SessionTest.php
  Tests/Unit/Templating/TemplateHelperTest.php
  Tests/Unit/ViewHelpers/AbstractConfigurationCheckViewHelperTest.php
  Tests/Unit/ViewHelpers/DynamicDateViewHelperTest.php
  Tests/Unit/ViewHelpers/IsFieldEnabledViewHelperTest.php
Labels: cleanup

#1258 [TASK] Stop using Prophecy in the functional tests
  CHANGELOG.md
  Tests/Functional/Templating/TemplateHelperTest.php
  Tests/Functional/Testing/TestingFrameworkTest.php
Labels: cleanup

#1259 [TASK] Drop the Prophecy dependency
  .github/workflows/ci.yml
  CHANGELOG.md
  composer.json
Labels: dependencies

#1260 [CLEANUP] Make properties in tests private where possible
  Tests/Functional/Model/AbstractModelTest.php
  Tests/Functional/Validation/AbstractConfigurationDependentValidatorTest.php
  Tests/Unit/Geocoding/GeoCalculatorTest.php
  Tests/Unit/Templating/TemplateTest.php
  Tests/Unit/ViewHelpers/AbstractConfigurationCheckViewHelperTest.php
  Tests/Unit/ViewHelpers/DynamicDateViewHelperTest.php
  Tests/Unit/ViewHelpers/IsFieldEnabledViewHelperTest.php
Labels: cleanup
