Repository oliverklee/ext-oelib, pull requests merged in 2024-02, with the labels that each got.

#1726 [FEATURE] Add Rector to CI
  .github/workflows/ci.yml
Labels: enhancement

#1731 [CLEANUP] Use more arrow functions in the tests
  Tests/Unit/DataStructures/CollectionTest.php
Labels: cleanup

#1727 [TASK] Unify the spelling of "email"
  Classes/Configuration/AbstractConfigurationCheck.php
  Classes/Email/GeneralEmailRole.php
  Classes/Interfaces/MailRole.php
  Classes/Model/BackEndUser.php
  Classes/Model/FrontEndUser.php
  Documentation/Introduction/Credits/Index.rst
  Documentation/Introduction/KeyFeatures/Index.rst
  Documentation/Tutorial/StoreHttpHeadersForTestingThemInsteadOfSendingThem/Index.rst
  Tests/Unit/Model/BackEndUserTest.php
  Tests/Unit/Model/FrontEndUserTest.php
Labels: hacktoberfest
